$doc_start = <<END_OF_STRING
<?xml version="1.0" encoding="UTF-8" ?>
<!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
<!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
<!-- You may use this file to transfer that content from one site to another. -->
<!-- This file is not intended to serve as a complete backup of your site. -->

<!-- To import this information into a WordPress site follow these steps: -->
<!-- 1. Log in to that site as an administrator. -->
<!-- 2. Go to Tools: Import in the WordPress admin panel. -->
<!-- 3. Install the "WordPress" importer from the list. -->
<!-- 4. Activate & Run Importer. -->
<!-- 5. Upload this file using the form provided on that page. -->
<!-- 6. You will first be asked to map the authors in this export file to users -->
<!--    on the site. For each author, you may choose to map to an -->
<!--    existing user on the site or to create a new user. -->
<!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
<!--    contained in this file into your site. -->


<rss version="2.0"
	xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:wp="http://wordpress.org/export/1.2/"
>

<channel>
	<title>Ryttargårdskyrkan</title>
	<link>http://localhost:8888</link>
	<description>Ryttargårdskyrkan</description>
	<pubDate>Sun, 12 Aug 2012 17:00:00 +0000</pubDate>
	<language>sv-SE</language>
	<wp:wxr_version>1.2</wp:wxr_version>
	<wp:base_site_url>http://localhost:8888</wp:base_site_url>
	<wp:base_blog_url>http://localhost:8888</wp:base_blog_url>

	<wp:author><wp:author_id>1</wp:author_id><wp:author_login>admin</wp:author_login><wp:author_email>admin@ebilen.se</wp:author_email><wp:author_display_name><![CDATA[admin]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>
	<wp:term><wp:term_id>9</wp:term_id><wp:term_taxonomy>nav_menu</wp:term_taxonomy><wp:term_slug>huvudmeny</wp:term_slug><wp:term_name><![CDATA[Huvudmeny]]></wp:term_name></wp:term>

END_OF_STRING

$page_content_default = <<END_OF_STRING
END_OF_STRING

$page_template = <<END_OF_STRING
	<item>
		<title>[TITLE]</title>
		<link>http://localhost:8888/[PERMALINK]</link>
		<pubDate>Sun, 12 Aug 2012 17:00:00 +0000</pubDate>
		<dc:creator>admin</dc:creator>
		<guid isPermaLink="false">http://localhost:8888/?page_id=[ID]</guid>
		<description></description>
		<content:encoded><![CDATA[[CONTENT]]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>[ID]</wp:post_id>
		<wp:post_date>2012-08-12 18:00:00</wp:post_date>
		<wp:post_date_gmt>2012-08-12 18:00:00</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>[NAME]</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>[PAGE_PARENT_ID]</wp:post_parent>
		<wp:menu_order>[MENU_ORDER]</wp:menu_order>
		<wp:post_type>page</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<wp:postmeta>
			<wp:meta_key>_edit_last</wp:meta_key>
			<wp:meta_value><![CDATA[1]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_wp_page_template</wp:meta_key>
			<wp:meta_value><![CDATA[[TEMPLATE]]]></wp:meta_value>
		</wp:postmeta>
	</item>
END_OF_STRING

$top_menu_template = <<END_OF_STRING
	<item>
		<title>[TITLE]</title>
		<link>http://localhost:8888/?p=[ID]</link>
		<pubDate>Sun, 12 Aug 2012 17:00:00 +0000</pubDate>
		<dc:creator>admin</dc:creator>
		<guid isPermaLink="false">http://localhost:8888/?p=[ID]</guid>
		<description></description>
		<content:encoded><![CDATA[]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>[ID]</wp:post_id>
		<wp:post_date>2012-08-12 18:00:00</wp:post_date>
		<wp:post_date_gmt>2012-08-12 18:00:00</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>[NAME]</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>0</wp:post_parent>
		<wp:menu_order>[MENU_ORDER]</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="huvudmeny"><![CDATA[Huvudmeny]]></category>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[0]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[[ID]]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[custom]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[#]]></wp:meta_value>
		</wp:postmeta>
	</item>
END_OF_STRING


$tsave = <<END_OF_STRING
		<wp:postmeta>
			<wp:meta_key>_menu_item_orphaned</wp:meta_key>
			<wp:meta_value><![CDATA[1347131590]]></wp:meta_value>
		</wp:postmeta>
END_OF_STRING




$page_menu_template = <<END_OF_STRING
	<item>
		<title></title>
		<link>http://localhost:8888/blogg/[ID]/</link>
		<pubDate>Sun, 12 Aug 2012 17:00:00 +0000</pubDate>
		<dc:creator>admin</dc:creator>
		<guid isPermaLink="false">http://localhost:8888/?p=[ID]</guid>
		<description></description>
		<content:encoded><![CDATA[ ]]></content:encoded>
		<excerpt:encoded><![CDATA[]]></excerpt:encoded>
		<wp:post_id>[ID]</wp:post_id>
		<wp:post_date>2012-08-12 18:00:00</wp:post_date>
		<wp:post_date_gmt>2012-08-12 18:00:00</wp:post_date_gmt>
		<wp:comment_status>open</wp:comment_status>
		<wp:ping_status>open</wp:ping_status>
		<wp:post_name>[ID]</wp:post_name>
		<wp:status>publish</wp:status>
		<wp:post_parent>[PAGE_PARENT_ID]</wp:post_parent>
		<wp:menu_order>[MENU_ORDER]</wp:menu_order>
		<wp:post_type>nav_menu_item</wp:post_type>
		<wp:post_password></wp:post_password>
		<wp:is_sticky>0</wp:is_sticky>
		<category domain="nav_menu" nicename="huvudmeny"><![CDATA[Huvudmeny]]></category>
		<wp:postmeta>
			<wp:meta_key>_menu_item_type</wp:meta_key>
			<wp:meta_value><![CDATA[post_type]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_menu_item_parent</wp:meta_key>
			<wp:meta_value><![CDATA[[MENU_ITEM_PARENT_ID]]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object_id</wp:meta_key>
			<wp:meta_value><![CDATA[[MENU_ITEM_OBJECT_ID]]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_object</wp:meta_key>
			<wp:meta_value><![CDATA[page]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_target</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_classes</wp:meta_key>
			<wp:meta_value><![CDATA[a:1:{i:0;s:0:"";}]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_xfn</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
		<wp:postmeta>
			<wp:meta_key>_menu_item_url</wp:meta_key>
			<wp:meta_value><![CDATA[]]></wp:meta_value>
		</wp:postmeta>
	</item>
END_OF_STRING

$doc_end = <<END_OF_STRING
</channel>
</rss>
END_OF_STRING

$id_counter = 10


class Container
  def initialize()
    @children = Array.new
  end

  def add(child)
    @children.push(child)
    return self
  end

  def write(file)
    @children.each do |child|
      child.write(file, 0, 0, "")
    end
  end
end

class MenuTop
  def initialize(name, title)
    @name = name
    @title = title
    @children = Array.new
  end

  def add(child)
    @children.push(child)
    return self
  end

  def write(file, parent_menu_id, parent_page_id, parent_path)
    menu_id = $id_counter
    $id_counter += 1
    menu_order = "0";

    # Write menu item
    text = $top_menu_template.clone
    text.gsub!("[ID]", "#{menu_id}")
    text.gsub!("[NAME]", @name)
    text.gsub!("[TITLE]", @title)
    text.gsub!("[MENU_ORDER]", menu_order)
    file.puts(text)

    @children.each do |child|
      child.write(file, menu_id, parent_page_id, "")
    end
  end
end

class HomePage
  def write(file, menu_parent_id, page_parent_id, parent_path)
    page_id = $id_counter
    $id_counter += 1

    # Write page
    text = $page_template.clone
    text.gsub!("[ID]", "#{page_id}")
    text.gsub!("[NAME]", "hem")
    text.gsub!("[TITLE]", "Hem")
    text.gsub!("[PERMALINK]", "")
    text.gsub!("[MENU_ORDER]", "-1")
    text.gsub!("[TEMPLATE]", "page-front.php")
    text.gsub!("[PAGE_PARENT_ID]", "-1")

    filename = "home.html"
    if (File.exist?(filename))
      contentfile = File.open(filename, "rb")
      text.gsub!("[CONTENT]", contentfile.read)
    else
      text.gsub!("[CONTENT]", $page_content_default)
    end

    file.puts(text)
  end
end

class Page
  def initialize(name, title, template)
    @name = name
    @title = title
    @template = template
    @children = Array.new
  end

  def add(child)
    @children.push(child)
    return self
  end

  def write(file, menu_parent_id, page_parent_id, parent_path)
    page_id = $id_counter
    menu_id = $id_counter + 1
    $id_counter += 2

    permalink = "";
    menu_order = "0";
    menu_title = ""
    filename = ""

    if (parent_path.empty?)
      page_parent_id = 0;
      menu_title = @title
      permalink = "#{@name}"
      filename = "#{@name}.html"
    else
      permalink = "#{parent_path}/#{@name}"
      filename = "#{parent_path}_#{@name}.html"
    end

    # Write page
    text = $page_template.clone
    text.gsub!("[ID]", "#{page_id}")
    text.gsub!("[NAME]", @name)
    text.gsub!("[TITLE]", @title)
    text.gsub!("[PERMALINK]", permalink)
    text.gsub!("[MENU_ORDER]", menu_order)
    text.gsub!("[TEMPLATE]", @template)
    text.gsub!("[PAGE_PARENT_ID]", "#{page_parent_id}")
    
    if (File.exist?(filename))
      contentfile = File.open(filename, "rb")
      text.gsub!("[CONTENT]", contentfile.read)
    else
      text.gsub!("[CONTENT]", $page_content_default)
    end
    
    file.puts(text)

    # Write menu item
    text = $page_menu_template.clone
    text.gsub!("[ID]", "#{menu_id}")
    text.gsub!("[TITLE]", "#{menu_title}")
    text.gsub!("[PAGE_PARENT_ID]", "#{page_parent_id}")
    text.gsub!("[MENU_ITEM_OBJECT_ID]", "#{page_id}")
    text.gsub!("[MENU_ITEM_PARENT_ID]", "#{menu_parent_id}")
    text.gsub!("[MENU_ORDER]", menu_order)
    file.puts(text)

    @children.each do |child|
      child.write(file, menu_id, page_id, permalink)
    end
  end
end


File.open('wordpress-content.xml', 'w') do |out|

  container = Container.new(). \
    # Home
    add(HomePage.new()). \
    # Möten
    add(MenuTop.new("moten", "Möten") \
      .add(Page.new("moten", "Möten", "page-groups.php") \
        .add(Page.new("gudstjanst", "Gudstjänst", "page-group.php")) \
        .add(Page.new("pa-arabiska", "På arabiska", "page-group.php")) \
        .add(Page.new("cellgrupp", "Cellgrupp", "page-group.php")) \
        .add(Page.new("bon", "Bön", "page-group.php")) \
      ) \
    ). \
    # Undervisning
    add(MenuTop.new("undervisning", "Undervisning") \
      .add(Page.new("undervisning", "Undervisning", "page-groups.php") \
        .add(Page.new("predikningar", "Predikningar", "page-group.php")) \
        .add(Page.new("alpha", "Alpha", "page-group.php")) \
        .add(Page.new("steg-in-i-forsamling", "Steg in i forsamling", "page-group.php")) \
        .add(Page.new("aktenskapskurs", "Äktenskapskurs", "page-group.php")) \
      ) \
    ). \
    # Barn
    add(MenuTop.new("barn", "Barn") \
      .add(Page.new("barn", "Barn", "page-groups.php") \
        .add(Page.new("barn-babyrytmik", "Barn- och babyrytmik", "page-group.php")) \
        .add(Page.new("lofteslandet", "Löfteslandet", "page-group.php")) \
        .add(Page.new("barnkoren-hogtryck", "Barnkören H&ouml;gtryck", "page-group.php")) \
        .add(Page.new("scout", "Scout", "page-group.php")) \
        .add(Page.new("fritids", "Fritids", "page-group.php")) \
        .add(Page.new("lager", "Läger", "page-group.php")) \
      ) \
    ). \
    # Ungdom
    add(MenuTop.new("ungdom", "Ungdom") \
      .add(Page.new("ungdom", "Ungdom", "page-groups.php") \
        .add(Page.new("enter", "Enter", "page-group.php")) \
        .add(Page.new("konfa", "Konfa", "page-group.php")) \
        .add(Page.new("teenstreet", "TeenStreet", "page-group.php")) \
      ) \
    ). \
    # Pensionär
    add(MenuTop.new("pensionar", "Pensionär") \
      .add(Page.new("pensionar", "Pensionär", "page-groups.php") \
        .add(Page.new("rpg65plus", "RPG 65+", "page-group.php")) \
      ) \
    ). \
    # Musik
    add(MenuTop.new("musik", "Musik") \
      .add(Page.new("musik", "Musik", "page-groups.php") \
        .add(Page.new("vox-deo", "Vox Deo", "page-group.php")) \
        .add(Page.new("brasset", "Brasset", "page-group.php")) \
      ) \
    ). \
    # Mission
    add(MenuTop.new("mission", "Mission") \
      .add(Page.new("mission", "Mission", "page-groups.php") \
        .add(Page.new("missionsradet", "Missionsrådet", "page-group.php")) \
        .add(Page.new("missionsstipendium", "Missionsstipendium", "page-group.php")) \
      ) \
    ). \
    # Konferens
    add(MenuTop.new("konferens", "Konferens") \
      .add(Page.new("konferens", "Konferens", "page-groups.php") \
        .add(Page.new("lokaler", "Lokaler", "page-group.php")) \
      ) \
    ). \
    # Ryttargården
    add(MenuTop.new("ryttargarden", "Ryttargården") \
      .add(Page.new("ryttargarden", "Ryttargården", "page-group.php") \
      ) \
    ). \
    # Församlingen
    add(MenuTop.new("forsamlingen", "Församlingen") \
      .add(Page.new("forsamlingen", "Församlingen", "page-groups.php") \
        .add(Page.new("om-forsamlingen", "Om församlingen", "page-group.php")) \
        .add(Page.new("personal", "Personal", "page-group.php")) \
        .add(Page.new("forsamlingsledningen", "Församlingsledningen", "page-group.php")) \
        .add(Page.new("visionen", "Visionen", "page-group.php")) \
        .add(Page.new("medlemskap", "Medlemskap", "page-group.php")) \
        .add(Page.new("historik", "Historik", "page-group.php")) \
      ) \
    ). \
    # Församlingen internt
    add(MenuTop.new("forsamlingen-internt", "Församlingen internt") \
      .add(Page.new("forsamlingen-internt", "Församlingen internt", "page-groups.php") \
        .add(Page.new("ljus-och-bild", "Ljus och Bild", "page-group.php")) \
        .add(Page.new("epostlistor", "Epostlistor", "page-group.php")) \
        .add(Page.new("websidan", "Websidan", "page-group.php")) \
      ) \
    ). \
    # Kalender
    add(MenuTop.new("kalender", "Kalender") \
      .add(Page.new("kalender", "Kalender", "page-calendar-rosette.php") \
      ) \
    )

  out.puts($doc_start)
  container.write(out)
  out.puts($doc_end)
end